### ISSUE TITLE
这是怎么用的？

### ISSUE THREAD

**Issue by c0mpr3h3n510n** [History-exe/Pocket-Game-Maker-v0.83#1]
如果要像样品一样在PSP上开发游戏，如何怎么做？希望师父能教一教。

**Comment by History-exe** [comment]
开发很简单，甚至不需要编程基础。我正在基于旧版本的说明撰写新版的教程，请期待。（师傅谈不上，我也是小白）

**Comment by FeiZhaixiage** [comment]
请问能否上传旧版本说明呢？

**Comment by History-exe** [comment]
@zpxrainbowdash 可以，不过我近期不能上传，需要整理文件。另外不要对这个pgm抱有太大希望，我在移植过程中遇到了很多问题，移植的游戏经常随机无缘由卡死。可能是这个版本的pgm有内存泄漏。

**Comment by FeiZhaixiage** [comment]
应该不是引擎的原因 因为在《缘之空》psp移植版就是用的PGM0.83 (使用iso)在我游玩时并没有出现过一次崩溃（psp系统6.61固化 2000机型）
[从缘之空iso中提取的bin文件.zip](https://github.com/History-exe/Pocket-Game-Maker-v0.83/files/4817067/iso.bin.zip)

**Comment by History-exe** [comment]
暂时上传了旧版本的使用说明，里面描述的版本与最新的PGM有所不同，也有一些错误。
I temporarily uploaded the old version of the instructions, the version described in it is different from the latest PGM, and there are some errors.

**Comment by FeiZhaixiage** [comment]
感谢上传

**Comment by History-exe** [comment]
教程快出来了，再稍微等一等。中文版教程基本完成，在写英文本教程。

**Comment by History-exe** [comment]
https://github.com/History-exe/PGM_CE 现代版简易教程已经撰写完毕。
